#!/bin/sh
# mkroots.sh - regenerate tls_roots.h from the DER files in tls_roots_src/.
#
# Provenance of each root (2026 web PKI reality; everything a real site
# chains to is one of these):
#
#   isrg_root_x1.der          Let's Encrypt ISRG Root X1 (RSA, older chains)
#                             https://letsencrypt.org/certs/isrg-root-x1.pem
#   isrg_root_x2.der          Let's Encrypt ISRG Root X2 (ECDSA P-384, current)
#                             https://letsencrypt.org/certs/isrg-root-x2.pem
#   digicert_global_root_g2.der  DigiCert Global Root G2 (RSA)
#                             https://cacerts.digicert.com/DigiCertGlobalRootG2.crt
#   globalsign_root_r3.der    GlobalSign Root CA R3 (RSA)
#                             https://secure.globalsign.com/cacert/root-r3.crt
#   gts_root_r4.der           Google Trust Services Root R4 (ECDSA P-384)
#                             https://pki.goog/repo/certs/gtsr4.pem
#   sslcom_ecc_2022.der       SSL.com TLS ECC Root CA 2022 (Cloudflare ECC chains)
#   sslcom_rsa_2022.der       SSL.com TLS RSA Root CA 2022 (Cloudflare RSA chains)
#
# The two SSL.com roots have no stable public URL; they are extracted from
# the certificate chain example.com serves (openssl s_client -showcerts,
# ECDHE-ECDSA and ECDHE-RSA respectively). The build never runs this
# script: tls_roots.h is a committed input, regenerated only when the root
# set changes.

set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/tls_roots_src"
OUT="$HERE/tls_roots.h"

python3 - "$SRC" "$OUT" <<'PYEOF'
import sys

src, out = sys.argv[1], sys.argv[2]

roots = [
    ("isrg_root_x1", "tls_der_isrg_root_x1", "ISRG Root X1 (Let's Encrypt, RSA)"),
    ("isrg_root_x2", "tls_der_isrg_root_x2", "ISRG Root X2 (Let's Encrypt, ECDSA P-384)"),
    ("digicert_global_root_g2", "tls_der_digicert_global_root_g2", "DigiCert Global Root G2 (RSA)"),
    ("globalsign_root_r3", "tls_der_globalsign_root_r3", "GlobalSign Root CA R3 (RSA)"),
    ("gts_root_r4", "tls_der_gts_root_r4", "Google Trust Services Root R4 (ECDSA P-384)"),
    ("gts_root_r1", "tls_der_gts_root_r1", "Google Trust Services Root R1 (RSA)"),
    ("sslcom_ecc_2022", "tls_der_sslcom_ecc_2022", "SSL.com TLS ECC Root CA 2022"),
    ("sslcom_rsa_2022", "tls_der_sslcom_rsa_2022", "SSL.com TLS RSA Root CA 2022"),
]

lines = [
    "/* tls_roots.h - embedded CA roots (DER), generated by mkroots.sh.",
    " *",
    " * The build only verifies a presented chain against this table,",
    " * never trusts anything outside it. See mkroots.sh for the",
    " * provenance of every entry. TLS_ROOT_COUNT is defined in tls.h",
    " * and must equal the table size.",
    " */",
    "",
]

entries = []
for fname, cname, desc in roots:
    data = open(src + "/" + fname + ".der", "rb").read()
    lines.append("/* %s */" % desc)
    lines.append("static const unsigned char %s[%d] = {" % (cname, len(data)))
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    entries.append((cname, len(data)))

lines.append("const struct tls_root tls_roots[TLS_ROOT_COUNT] = {")
for cname, size in entries:
    lines.append("    { %s, %d }," % (cname, size))
lines.append("};")
lines.append("")

open(out, "w").write("\n".join(lines))
print("wrote %s (%d roots)" % (out, len(roots)))
PYEOF
